'use client';
import {useState} from 'react';
import {Slot,slotId,slotStart,slotEnd,minutes} from '@/lib/diary-data';
import {clockPoint,arcPath} from './time-range-picker';
const palette=['#8074cd','#3da99f','#e79b62','#d67e9d','#699bd0','#a3aa57'];
export default function DayClock({slots,onSelect}:{slots:Slot[];onSelect:(id:string)=>void}){
 const [mode,M]=useState<'plan'|'actual'>('plan');const [selected,S]=useState('');const active=slots.filter(s=>!s.archived);const filled=active.filter(s=>(mode==='plan'?s.plan:s.actual).trim());const chosen=filled.find(s=>slotId(s)===selected)||filled[0];
 return <section className="panel day-overview"><div className="overview-heading"><div><h2>하루를 한눈에</h2><p>구간을 선택해 내용을 보고 시간을 조절하세요</p></div><div className="clock-tabs"><button aria-pressed={mode==='plan'} onClick={()=>M('plan')}>계획</button><button aria-pressed={mode==='actual'} onClick={()=>M('actual')}>실제 활동</button></div></div><div className="overview-body"><svg className="day-clock" viewBox="0 0 300 300" aria-label={'24시간 '+(mode==='plan'?'계획':'실제 활동')+' 원형 시간표'}><circle cx="150" cy="150" r="111" fill="#f1f4f8"/>{filled.map((s,i)=>{const a=minutes(slotStart(s)),b=minutes(slotEnd(s)),p=clockPoint(a,108);const path=`M 150 150 L ${p.x} ${p.y} ${arcPath(a,b).replace(/^M [^A]+A/,'A')} Z`;return <path key={slotId(s)} d={path} fill={palette[i%palette.length]} stroke="white" strokeWidth="2" opacity={chosen&&slotId(chosen)!==slotId(s)?.7:1} role="button" tabIndex={0} aria-label={`${slotStart(s)}–${slotEnd(s)} ${mode==='plan'?s.plan:s.actual}`} onClick={()=>S(slotId(s))} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();S(slotId(s));}}}><title>{slotStart(s)}–{slotEnd(s)} · {mode==='plan'?s.plan:s.actual}</title></path>;})}{[0,3,6,9,12,15,18,21].map(h=>{const p=clockPoint(h*60,136);return <text key={h} x={p.x} y={p.y+4} textAnchor="middle" fontSize="11" fill="#697a91">{String(h).padStart(2,'0')}</text>;})}<circle cx="150" cy="150" r="30" fill="white"/><text x="150" y="146" textAnchor="middle" fontSize="12" fill="#65758a">하루</text><text x="150" y="164" textAnchor="middle" fontSize="15" fontWeight="700" fill="#172b45">24h</text></svg><div className="clock-detail">{chosen?<><span className="clock-range">{slotStart(chosen)}–{slotEnd(chosen)}</span><h3>{(mode==='plan'?'계획':'실제로 한 일')}</h3><p className="clock-copy">{mode==='plan'?chosen.plan:chosen.actual}</p><button onClick={()=>onSelect(slotId(chosen))}>이 구간 시간 조절</button></>:<p className="hint">{mode==='plan'?'시간칸에 계획을 적으면 여기에 표시돼요':'시간을 지정한 실제 활동을 기록하면 여기에 표시돼요'}</p>}<div className="clock-legend">{filled.map((s,i)=><button key={slotId(s)} onClick={()=>S(slotId(s))} aria-pressed={chosen&&slotId(chosen)===slotId(s)}><i style={{background:palette[i%palette.length]}}/><span>{slotStart(s)} · {(mode==='plan'?s.plan:s.actual).split('\n')[0]}</span></button>)}</div><small>회색은 기록 없는 시간 · 시간 미지정 활동은 메모에 표시</small></div></div></section>;
}
