'use client';
import { useState,useEffect,useRef } from 'react';
import { type Diary,type Slot,type NoteColor,noteColors,validDate,slotId,slotStart,slotEnd,validSlotTime,minutes } from '@/lib/diary-data';
import TimeRangePicker from './time-range-picker';
import DayClock from './day-clock';
const weekdays=['일','월','화','수','목','금','토'];
function today(){return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());}
function shift(date:string,n:number){const d=new Date(date+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10);}
export default function DiaryApp(){
 const [editingTime,setEditingTime]=useState<string|null>(null);const [date,setDate]=useState('');const [diary,setDiary]=useState<Diary|null>(null);const [revision,setRevision]=useState(0);const [dirty,setDirty]=useState(false);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState('');const [savedAt,setSavedAt]=useState<string|null>(null);const [isSaved,setIsSaved]=useState(false);const [quick,setQuick]=useState('');const [hour,setHour]=useState('');const [quickStatus,setQuickStatus]=useState<Slot['status']>('done');const [message,setMessageState]=useState('');const [toastId,setToastId]=useState(0);function setMessage(value:string){setMessageState(value);setToastId(n=>n+1);}const live=useRef<any>({});
 async function load(target:string){setLoading(true);setError('');setMessage('');setDiary(null);setQuick('');setHour('');setEditingTime(null);try{const r=await fetch('/api/diary?date='+encodeURIComponent(target),{cache:'no-store'});const data:any=await r.json();if(!r.ok)throw new Error(data.error||'불러오기에 실패했어요.');setDiary(data.diary);setRevision(data.revision);setSavedAt(data.updatedAt);setIsSaved(data.saved);setDirty(false);}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
 useEffect(()=>{const q=new URLSearchParams(window.location.search).get('date');const initial=validDate(q)?q:today();setDate(initial);void load(initial);},[]);
 useEffect(()=>{if(!message)return;const timer=window.setTimeout(()=>setMessage(''),4000);return()=>window.clearTimeout(timer);},[message,toastId]);
 useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(dirty||quick.trim()){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty,quick]);
 function move(target:string){if(!validDate(target)||saving||loading||target===date)return;if((dirty||quick.trim())&&!window.confirm('저장하지 않은 내용이 있어요. 저장하지 않고 날짜를 바꿀까요?'))return;setDate(target);const url=new URL(window.location.href);url.searchParams.set('date',target);window.history.replaceState(null,'',url.pathname+url.search);void load(target);}
 function updateField(key:'notes'|'summary'|'improvement'|'next',value:string){setDiary(d=>d?{...d,[key]:value,...(key==='notes'?{notesArchived:false}:{})}:d);setDirty(true);setMessage('');}
 function setNoteColor(id:string,color:NoteColor){setDiary(d=>d?id==='original'?{...d,notesColor:color}:{...d,stickyNotes:(d.stickyNotes||[]).map(n=>n.id===id?{...n,color}:n)}:d);setDirty(true);setMessage('');}
 function addNote(){if(!diary||(diary.stickyNotes||[]).length>=20)return;const id=crypto.randomUUID();setDiary(d=>d?{...d,stickyNotes:[...(d.stickyNotes||[]),{id,text:'',color:noteColors[((d.stickyNotes||[]).length+1)%noteColors.length]}]}:d);setDirty(true);setMessage('');requestAnimationFrame(()=>document.getElementById('note-'+id)?.focus());}
 function archiveNote(id:string,deleted:boolean){setDiary(d=>d?id==='original'?{...d,notesArchived:deleted}:{...d,stickyNotes:(d.stickyNotes||[]).map(n=>n.id===id?{...n,deleted}:n)}:d);setDirty(true);setMessage(deleted?'메모를 삭제했어요. 아래 ‘삭제한 메모’에서 복원할 수 있어요. 저장하면 반영됩니다.':'메모를 복원했어요. 저장하면 반영됩니다.');}
 function editNote(id:string,text:string){setDiary(d=>d?{...d,stickyNotes:(d.stickyNotes||[]).map(n=>n.id===id?{...n,text}:n)}:d);setDirty(true);setMessage('');}
 function colors(id:string,current:NoteColor){return <div className="note-colors" aria-label="메모 색상">{noteColors.map(c=><button key={c} type="button" className={'swatch '+c} aria-label={({yellow:'노랑',pink:'분홍',mint:'민트',blue:'파랑'}[c])+' 메모 색상'} aria-pressed={current===c} disabled={saving} onClick={()=>setNoteColor(id,c)}/>)}</div>;}
 function updateSlot(id:string,key:'plan'|'actual'|'status',value:string){setDiary(d=>d?{...d,slots:d.slots.map(s=>slotId(s)===id?{...s,[key]:value}:s)}:d);setDirty(true);setMessage('');}
 function addSlot(){if(!diary||saving||diary.slots.length>=48)return;const id=crypto.randomUUID();setDiary(d=>d?{...d,slots:[...d.slots,{id,hour:Math.max(21,...d.slots.map(s=>s.hour))+1,start:'09:00',end:'10:00',plan:'',actual:'',status:'planned'}]}:d);setDirty(true);setEditingTime(id);}
 function archiveSlot(id:string,archived:boolean){setDiary(d=>d?{...d,slots:d.slots.map(s=>slotId(s)===id?{...s,archived}:s)}:d);if(hour===id)setHour('');setDirty(true);setMessage(archived?'시간칸을 숨겼어요. 아래에서 복원할 수 있어요. 저장하면 반영됩니다.':'시간칸을 복원했어요.');}
 function applyTime(start:string,end:string){setDiary(d=>d?{...d,slots:d.slots.map(s=>slotId(s)===editingTime?{...s,start,end}:s)}:d);setDirty(true);setEditingTime(null);}
 function addRecord(text=quick,at=hour,status=quickStatus){if(!text.trim()||!diary||saving||loading)return false;const current=at===''?diary.notes:diary.slots.find(s=>slotId(s)===at&&!s.archived)?.actual;if(current===undefined)return false;const cap=at===''?12000:4000;if(current.length+text.trim().length+30>cap){setError('기록이 너무 길어요. 내용을 줄이거나 새 메모에 나누어 적어주세요.');return false;}if(at==='')updateField('notes',(diary.notes?diary.notes+'\n':'')+'['+({done:'완료',progress:'진행 중',planned:'기록'}[status])+'] '+text.trim());else{setDiary(d=>d?{...d,slots:d.slots.map(s=>slotId(s)===at&&!s.archived?{...s,actual:(s.actual?s.actual+'\n':'')+text.trim(),status}:s)}:d);setDirty(true);}setQuick('');setMessage('기록을 추가했어요. 상단의 저장을 누르면 보관됩니다.');return true;}
 async function save(){if(!diary||saving||loading)return false;if(!diary.slots.every(validSlotTime)){setError('각 시간칸의 종료 시간을 시작보다 늦게 선택해주세요.');return false;}if(quick.trim()){setMessage('한 줄 기록의 ‘추가’를 먼저 눌러주세요.');return false;}setSaving(true);setError('');setMessage('');try{const r=await fetch('/api/diary',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({date,diary,revision})});const data:any=await r.json();if(!r.ok)throw new Error(data.error||'저장에 실패했어요.');setRevision(data.revision);setSavedAt(data.updatedAt);setIsSaved(true);setDirty(false);setMessage('이 날짜의 기록을 저장했어요.');return true;}catch(e){setError((e as Error).message);return false;}finally{setSaving(false);}}
 live.current={date,diary,dirty,saving,move,addRecord,save};
 useEffect(()=>{const ctx=(document as any).modelContext;if(!ctx?.registerTool)return;const controller=new AbortController();const tools=[{name:'read_selected_diary',description:'Read the displayed date and current diary. May include unsaved user text.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:async()=>({date:live.current.date,diary:live.current.diary,unsaved:live.current.dirty})},{name:'stage_diary_activity',description:'Add an activity to the displayed diary as an unsaved edit. This does not save the record.',inputSchema:{type:'object',properties:{text:{type:'string'},slotId:{type:'string',description:'Stable row ID from read_selected_diary; legacy rows use legacy- plus hour'},status:{type:'string',enum:['planned','progress','done']}},required:['text'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:async(x:any)=>{if(typeof x.text!=='string'||!x.text.trim()||x.text.length>2000||x.slotId!==undefined&&typeof x.slotId!=='string'||x.status&&!['planned','progress','done'].includes(x.status))throw new Error('Invalid activity');return{staged:live.current.addRecord(x.text,x.slotId||'',x.status||'done'),saved:false};}}];for(const t of tools){try{Promise.resolve(ctx.registerTool(t,{signal:controller.signal})).catch(()=>{});}catch{}}return()=>controller.abort();},[]);
 const selected=date?new Date(date+'T12:00:00Z'):null;const done=diary?.slots.filter(s=>!s.archived&&s.status==='done'&&s.actual.trim())||[];const progress=diary?.slots.filter(s=>!s.archived&&s.status==='progress'&&s.actual.trim())||[];
 const activeSlots=(diary?.slots||[]).filter(s=>!s.archived).slice().sort((a,b)=>slotStart(a).localeCompare(slotStart(b)));
 const timeSlot=diary?.slots.find(s=>slotId(s)===editingTime);
 const overlap=activeSlots.some((a,i)=>activeSlots.slice(i+1).some(b=>minutes(slotStart(a))<minutes(slotEnd(b))&&minutes(slotStart(b))<minutes(slotEnd(a))));
 return <><header><div className="header-inner"><div><div className="eyebrow">RESEARCH DIARY</div><h1>My Research Diary</h1><p>계획을 세우고, 실제로 한 일을 남기는 하루</p></div><span className="private">나만의 기록</span></div></header>
 <div className="toolbar"><div className="date-controls"><button aria-label="이전 날" disabled={loading||saving} onClick={()=>move(shift(date,-1))}>‹</button><label className="date-label"><span className="sr-only">기록 날짜</span><input aria-label="기록 날짜" type="date" value={date} onChange={e=>move(e.target.value)} disabled={loading||saving}/></label><span className="weekday">{selected?weekdays[selected.getUTCDay()]+'요일':''}</span><button aria-label="다음 날" disabled={loading||saving} onClick={()=>move(shift(date,1))}>›</button><button className="today" disabled={loading||saving} onClick={()=>move(today())}>오늘</button></div><div className="save-area"><span role="status" className={dirty?'unsaved':'save-status'}>{saving?'저장 중…':dirty?'저장하지 않은 변경':isSaved?'저장됨':'아직 저장하지 않은 초안'}</span><button className="primary" disabled={saving||loading||!diary} onClick={save}>{saving?'저장 중…':'변경사항 저장'}</button></div></div>
 <main><div className="week-strip" aria-label="선택한 날짜 주변 일주일">{date&&Array.from({length:7},(_,i)=>shift(date,i-3)).map(d=><button disabled={loading||saving} key={d} className={d===date?'selected':''} onClick={()=>move(d)}><span>{weekdays[new Date(d+'T12:00:00Z').getUTCDay()]}</span><strong>{Number(d.slice(8))}</strong>{d===today()&&<small>오늘</small>}</button>)}</div>
 {error&&<div role="alert" className="error">{error}<button disabled={saving} onClick={()=>{if((dirty||quick.trim())&&!window.confirm('다시 불러오면 저장하지 않은 입력이 사라집니다. 필요한 내용을 복사했나요?'))return;void load(date);}}>다시 불러오기</button></div>}
 {message&&<div role="status" aria-live="polite" className="toast"><span className="toast-icon" aria-hidden="true">✓</span><span>{message}</span><button aria-label="알림 닫기" onClick={()=>setMessage('')}>×</button></div>}
 {loading?<div className="loading">기록을 불러오는 중…</div>:diary&&<><section className="quick panel"><div><h2>한 줄 기록</h2><p>“논문 정리함”처럼 짧게 남겨도 좋아요</p></div><div className="quick-form"><input aria-label="한 줄 활동 기록" placeholder="무엇을 했나요?" value={quick} maxLength={2000} disabled={saving} onChange={e=>setQuick(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.nativeEvent.isComposing){e.preventDefault();addRecord();}}}/><select aria-label="기록 시간" value={hour} disabled={saving} onChange={e=>setHour(e.target.value)}><option value="">시간 미지정</option>{activeSlots.map(s=><option value={slotId(s)} key={slotId(s)}>{slotStart(s)}–{slotEnd(s)}{s.plan?' · '+s.plan.slice(0,16):''}</option>)}</select><select aria-label="활동 상태" value={quickStatus} disabled={saving} onChange={e=>setQuickStatus(e.target.value as Slot['status'])}><option value="done">완료</option><option value="progress">진행 중</option><option value="planned">기록</option></select><button className="primary" disabled={saving||!quick.trim()} onClick={()=>addRecord()}>추가</button></div></section>
 <DayClock slots={diary.slots} onSelect={setEditingTime}/><div className="layout"><section className="panel timetable"><div className="panel-heading"><h2>시간별 다이어리</h2><button onClick={addSlot} disabled={saving||diary.slots.length>=48}>＋ 시간칸</button></div><p className="time-help">시간을 누르면 원형 시계에서 범위를 고를 수 있어요</p>{overlap&&<p className="time-warning">겹치는 시간칸이 있어요. 함께 기록하거나, 필요 없는 칸은 숨길 수 있어요.</p>}<div className="columns"><span>시간</span><span>계획</span><span>실제로 한 일</span></div>{activeSlots.map(s=><div className="diary-row" key={slotId(s)}><div className="time"><button className="time-range-button" disabled={saving} aria-label={slotStart(s)+'부터 '+slotEnd(s)+' 시간 변경'} onClick={()=>setEditingTime(slotId(s))}><strong>{slotStart(s)}</strong><span>– {slotEnd(s)}</span><small>{minutes(slotEnd(s))-minutes(slotStart(s))}분</small></button><button className="hide-slot" disabled={saving} onClick={()=>archiveSlot(slotId(s),true)}>칸 숨기기</button></div><label className="cell"><span className="mobile-label">계획</span><textarea aria-label={`${slotStart(s)}–${slotEnd(s)} 계획`} maxLength={2000} disabled={saving} value={s.plan} placeholder="예정한 일" onChange={e=>updateSlot(slotId(s),'plan',e.target.value)}/></label><div className="cell actual"><label><span className="mobile-label">실제로 한 일</span><textarea aria-label={`${slotStart(s)}–${slotEnd(s)} 실제 활동`} maxLength={4000} disabled={saving} value={s.actual} placeholder="한 일이나 막힌 점을 자유롭게" onChange={e=>updateSlot(slotId(s),'actual',e.target.value)}/></label><select aria-label={`${slotStart(s)}–${slotEnd(s)} 진행 상태`} value={s.status} disabled={saving} onChange={e=>updateSlot(slotId(s),'status',e.target.value)}><option value="planned">미표시</option><option value="progress">진행 중</option><option value="done">완료</option></select></div></div>)}{diary.slots.some(s=>s.archived)&&<details className="hidden-slots"><summary>숨긴 시간칸 ({diary.slots.filter(s=>s.archived).length})</summary>{diary.slots.filter(s=>s.archived).map(s=><div key={slotId(s)}><span>{slotStart(s)}–{slotEnd(s)} · {s.plan||s.actual||'빈 시간칸'}</span><button disabled={saving} onClick={()=>archiveSlot(slotId(s),false)}>복원</button></div>)}</details>}{diary.slots.length>=48&&<p className="time-help">숨긴 칸을 포함해 하루 48칸까지 보관할 수 있어요</p>}</section>
 <aside><section className="panel"><h2>선택한 날의 진행</h2><div className="counts"><div><strong>{done.length}</strong><span>완료 시간칸</span></div><div><strong>{progress.length}</strong><span>진행 중 시간칸</span></div></div><p className="hint">실제 활동을 적고 상태를 선택한 칸 기준이에요. 수행 시간이나 생산성 점수가 아닙니다.</p>{done.length>0&&<ul className="done-list">{done.map(s=><li key={slotId(s)}><span>{slotStart(s)}–{slotEnd(s)}</span>{s.actual}</li>)}</ul>}</section>
 <section className="sticky-board" aria-label="날짜별 스티커 메모"><div className="board-heading"><h2>오늘의 메모</h2><button onClick={addNote} disabled={saving||(diary.stickyNotes||[]).length>=20}>＋ 메모</button></div><p className="hint">떠오른 생각이나 시간표 밖 기록을 붙여두세요</p><div className="sticky-stack">{!diary.notesArchived&&<article className={'sticky-note '+(diary.notesColor||'yellow')}><div className="note-top"><span>시간 미지정 기록</span>{colors('original',diary.notesColor||'yellow')}<button className="note-delete" aria-label="시간 미지정 메모 삭제" disabled={saving} onClick={()=>archiveNote('original',true)}>×</button></div><textarea className="sticky-text" aria-label="시간 미지정 기록과 메모" maxLength={12000} disabled={saving} value={diary.notes} onChange={e=>updateField('notes',e.target.value)} placeholder="시간을 몰라도 괜찮아요.
짧게 한 일을 남겨보세요"/><span className="note-date">{date.slice(5).replace('-',' / ')}</span></article>}{(diary.stickyNotes||[]).filter(n=>!n.deleted).map((n,i)=><article className={'sticky-note '+n.color} key={n.id}><div className="note-top"><span>메모 {i+1}</span>{colors(n.id,n.color)}<button className="note-delete" aria-label={'메모 '+(i+1)+' 삭제'} disabled={saving} onClick={()=>archiveNote(n.id,true)}>×</button></div><textarea id={'note-'+n.id} className="sticky-text" aria-label={'추가 메모 '+(i+1)} maxLength={2000} disabled={saving} value={n.text} onChange={e=>editNote(n.id,e.target.value)} placeholder="아이디어, 질문, 잊지 않을 것…"/><span className="note-date">{date.slice(5).replace('-',' / ')}</span></article>)}{diary.notesArchived&&!(diary.stickyNotes||[]).some(n=>!n.deleted)&&<p className="empty-notes">붙여둔 메모가 없어요. ‘＋ 메모’로 시작하세요</p>}</div>{(diary.notesArchived||(diary.stickyNotes||[]).some(n=>n.deleted))&&<details className="deleted-notes"><summary>삭제한 메모 ({(diary.notesArchived?1:0)+(diary.stickyNotes||[]).filter(n=>n.deleted).length})</summary><p className="hint">저장 후에도 여기서 복원할 수 있어요</p>{diary.notesArchived&&<div><span>{diary.notes||'시간 미지정 메모'}</span><button disabled={saving} onClick={()=>archiveNote('original',false)}>복원</button></div>}{(diary.stickyNotes||[]).filter(n=>n.deleted).map(n=><div key={n.id}><span>{n.text||'빈 메모'}</span><button disabled={saving} onClick={()=>archiveNote(n.id,false)}>복원</button></div>)}</details>}{(diary.stickyNotes||[]).length>=20&&<p className="hint">추가 메모는 삭제한 메모를 포함해 하루 20장까지 보관돼요. 기존 메모를 복원해 수정할 수 있어요.</p>}<p className="hint">내용과 색상은 ‘변경사항 저장’을 누르면 보관돼요</p></section>
 <section className="panel info"><h2>기록을 오래 이어가기</h2><p>빈칸은 기록이 없는 시간이에요. 완료하지 못했다고 판단하지 않아요.</p><p>저장은 이 사이트에 보관됩니다. Notion 자동 연동과 예약 자동 요약은 아직 연결되지 않았어요.</p>{savedAt&&<p className="timestamp">마지막 저장<br/>{new Date(savedAt).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'})}</p>}</section></aside></div>
 <section className="panel reflection"><div className="panel-heading"><h2>하루 마무리</h2><span>직접 작성 · 저장 가능</span></div><div className="reflection-grid">{([{key:'summary',title:'오늘의 요약',placeholder:'무엇을 했고 어떤 결과를 남겼나요?'},{key:'improvement',title:'막힌 점 · 개선점',placeholder:'다음에는 무엇을 다르게 해볼까요?'},{key:'next',title:'다음에 이어갈 일',placeholder:'가장 먼저 할 일 한두 가지'}] as const).map(x=><label key={x.key}><strong>{x.title}</strong><textarea aria-label={x.title} disabled={saving} maxLength={12000} value={diary[x.key]} onChange={e=>updateField(x.key,e.target.value)} placeholder={x.placeholder}/></label>)}</div></section>
 <div className="bottom-save"><span>지난 날짜도 선택해서 수정할 수 있어요</span><button className="primary" onClick={save} disabled={saving}>{saving?'저장 중…':'이 날짜 기록 저장'}</button></div></>}
 </main>{timeSlot&&<TimeRangePicker start={slotStart(timeSlot)} end={slotEnd(timeSlot)} onApply={applyTime} onClose={()=>setEditingTime(null)}/>}<footer>연구 다이어리 · 한국 시간 기준</footer></>;
}
