'use client';
import {useEffect,useRef,useState} from 'react';
import {minutes,validTime} from '@/lib/diary-data';
export const clockPoint=(m:number,r=108)=>({x:150+r*Math.sin(m/1440*Math.PI*2),y:150-r*Math.cos(m/1440*Math.PI*2)});
export function arcPath(a:number,b:number,r=108){const p=clockPoint(a,r),q=clockPoint(b,r);return `M ${p.x} ${p.y} A ${r} ${r} 0 ${b-a>720?1:0} 1 ${q.x} ${q.y}`;}
const time=(m:number)=>`${String(Math.floor(m/60)).padStart(2,'0')}:${String(m%60).padStart(2,'0')}`;
export default function TimeRangePicker({start,end,onApply,onClose}:{start:string;end:string;onApply:(a:string,b:string)=>void;onClose:()=>void}){
 const [a,A]=useState(start),[b,B]=useState(end),[handle,H]=useState<'start'|'end'>('start');const dragging=useRef<'start'|'end'|null>(null);const panel=useRef<HTMLDivElement>(null);const svg=useRef<SVGSVGElement>(null);
 useEffect(()=>{const previous=document.activeElement as HTMLElement|null;panel.current?.focus();function key(e:KeyboardEvent){if(e.key==='Escape')onClose();if(e.key==='Tab'){const items=panel.current?.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled),[tabindex="0"]');if(!items?.length)return;const first=items[0],last=items[items.length-1];if(e.shiftKey&&(document.activeElement===first||document.activeElement===panel.current)){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}}document.addEventListener('keydown',key);return()=>{document.removeEventListener('keydown',key);previous?.focus();};},[]);
 const valid=validTime(a)&&validTime(b)&&minutes(b)>minutes(a);const duration=valid?minutes(b)-minutes(a):0;
 function pick(e:React.PointerEvent<SVGSVGElement>,target:'start'|'end'){const box=svg.current!.getBoundingClientRect();const x=(e.clientX-box.left)/box.width*300-150,y=(e.clientY-box.top)/box.height*300-150;let angle=Math.atan2(x,-y);if(angle<0)angle+=Math.PI*2;const m=Math.round(angle/(Math.PI*2)*1440/15)*15%1440;(target==='start'?A:B)(time(m));}
 const p=clockPoint(validTime(a)?minutes(a):0),q=clockPoint(validTime(b)?minutes(b):60);
 return <div className="time-modal-backdrop" onClick={e=>{if(e.target===e.currentTarget)onClose();}}><div className="time-modal" role="dialog" aria-modal="true" aria-labelledby="time-title" tabIndex={-1} ref={panel}><div className="modal-heading"><h2 id="time-title">시간 범위 선택</h2><button aria-label="시간 선택 닫기" onClick={onClose}>×</button></div><p>24시간 시계 · 시작과 끝 점을 움직여 선택하세요</p><div className="time-selection"><button aria-pressed={handle==='start'} onClick={()=>H('start')}>시작 {a}</button><span>→</span><button aria-pressed={handle==='end'} onClick={()=>H('end')}>종료 {b}</button></div>
 <svg ref={svg} viewBox="0 0 300 300" className="range-clock" aria-label="24시간 원형 시간 선택기. 아래 입력칸으로도 시간을 설정할 수 있습니다" onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);const box=e.currentTarget.getBoundingClientRect();const x=(e.clientX-box.left)/box.width*300,y=(e.clientY-box.top)/box.height*300;const dp=Math.hypot(x-p.x,y-p.y),dq=Math.hypot(x-q.x,y-q.y);const target=Math.min(dp,dq)<24?(dp<=dq?'start':'end'):handle;dragging.current=target;H(target);pick(e,target);}} onPointerMove={e=>{if(dragging.current)pick(e,dragging.current);}} onPointerUp={()=>dragging.current=null} onPointerCancel={()=>dragging.current=null}>
 <circle cx="150" cy="150" r="108" fill="none" stroke="#e8edf4" strokeWidth="22"/>{Array.from({length:24},(_,h)=>{const pt=clockPoint(h*60,136);return <text key={h} x={pt.x} y={pt.y+4} textAnchor="middle" fontSize="10" fill="#65758a">{h===0?'00':h}</text>;})}{valid&&<path d={arcPath(minutes(a),minutes(b))} fill="none" stroke="#6d73dc" strokeWidth="22" strokeLinecap="round"/>}<circle cx={p.x} cy={p.y} r="11" fill="#fff" stroke="#285bce" strokeWidth="4"/><circle cx={q.x} cy={q.y} r="11" fill="#fff" stroke="#087e87" strokeWidth="4"/><text x="150" y="146" textAnchor="middle" fontWeight="700" fontSize="22" fill="#172b45">{valid?`${Math.floor(duration/60)?Math.floor(duration/60)+'시간 ':''}${duration%60?duration%60+'분':''}`:'시간 확인'}</text><text x="150" y="170" textAnchor="middle" fontSize="12" fill="#65758a">{a}–{b}</text></svg>
 <div className="exact-time"><label>시작<input aria-label="시작 시각" type="time" value={a} onChange={e=>A(e.target.value)}/></label><label>종료<input aria-label="종료 시각" type="time" value={b} onChange={e=>B(e.target.value)}/></label></div><p className={valid?'time-picker-hint':'time-invalid'}>{valid?'시계는 15분 간격 · 입력칸에서는 분 단위로 조절 가능':'같은 날짜 안에서 종료를 시작보다 늦게 선택해주세요'}</p><div className="modal-actions"><button onClick={onClose}>취소</button><button className="primary" disabled={!valid} onClick={()=>onApply(a,b)}>시간 적용</button></div></div></div>;
}
